export const professionalResume = {
  'inklua-2023': [
    `<h1>John Doe</h1>`,
    `<p>Front-End Developer</p>`,
    `<section>`,
    `<h2>About Me</h2>`,
    `<p>I'm a passionate front-end developer</p>`,
    `</section>`,
    `<section>`,
    `<h2>Skills</h2>`,
    `<ul>`,
    `<li>HTML5</li>`,
    `<li>CSS3</li>`,
    `<li>JavaScript</li>`,
    `<li>React</li>`,
    `<li>Responsive Web Design</li>`,
    `</ul>`,
    `</section>`,
    `<section>`,
    `<h2>Experience</h2>`,
    `<div>`,
    `<h3>Front-End Developer at ABC Company</h3>`,
    `<p>Worked on developing user-friendly and responsive web applications using React.</p>`,
    `<p>Collaborated with designers to implement pixel-perfect UI designs.</p>`,
    `</div>`,
    `<div>`,
    `<h3>Web Developer Intern at XYZ Agency</h3>`,
    `<p>Assisted in the development of web projects, gaining hands-on experience with HTML, CSS, and JavaScript.</p>`,
    `</div>`,
    `</section>`,
    `<section>`,
    `<h2>Education</h2>`,
    `<div>`,
    `<h3>Bachelor of Science in Computer Science</h3>`,
    `<p>University of Front-End Development</p>`,
    `<p>Graduated Magna Cum Laude</p>`,
    `</div>`,
    `</section>`,
    `<section>`,
    `<h2>Contact</h2>`,
    `<p>Email: john.doe@example.com</p>`,
    `<p>LinkedIn: <a href="https://www.linkedin.com/in/johndoe" target="_blank">linkedin.com/in/johndoe</a></p>`,
    `</section>`
  ],
  'inklua-2022': [
    `<h1>John</h1>`,
    `<p>Front-End Developer</p>`,
    `<section>`,
    `<h2>About Me</h2>`,
    `<p>I'm a passionate front-end developer</p>`,
    `</section>`,
    `<section>`,
    `<h2>Skills</h2>`,
    `<ul>`,
    `<li>HTML5</li>`,
    `<li>CSS3</li>`,
    `<li>JavaScript</li>`,
    `<li>React</li>`,
    `<li>Responsive Web Design</li>`,
    `</ul>`,
    `</section>`,
    `<section>`,
    `<h2>Experience</h2>`,
    `<div>`,
    `<h3>Front-End Developer at ABC Company</h3>`,
    `<p>Worked on developing user-friendly and responsive web applications using React.</p>`,
    `<p>Collaborated with designers to implement pixel-perfect UI designs.</p>`,
    `</div>`,
    `<div>`,
    `<h3>Web Developer Intern at XYZ Agency</h3>`,
    `<p>Assisted in the development of web projects, gaining hands-on experience with HTML, CSS, and JavaScript.</p>`,
    `</div>`,
    `</section>`,
    `<section>`,
    `<h2>Education</h2>`,
    `<div>`,
    `<h3>Bachelor of Science in Computer Science</h3>`,
    `<p>University of Front-End Development</p>`,
    `<p>Graduated Magna Cum Laude</p>`,
    `</div>`,
    `</section>`,
    `<section>`,
    `<h2>Contact</h2>`,
    `<p>Email: john.doe@example.com</p>`,
    `<p>LinkedIn: <a href="https://www.linkedin.com/in/johndoe" target="_blank">linkedin.com/in/johndoe</a></p>`,
    `</section>`
  ],
  'inklua-2021': [
    `<h1>John Doe</h1>`,
    `<p>Front-End Developer</p>`,
    `<section>`,
    `<h2>About Me</h2>`,
    `<p>I'm a passionate front-end developer</p>`,
    `</section>`,
    `<section>`,
    `<h2>Skills</h2>`,
    `<ul>`,
    `<li>HTML5</li>`,
    `<li>CSS3</li>`,
    `<li>JavaScript</li>`,
    `<li>React</li>`,
    `<li>Responsive Web Design</li>`,
    `</ul>`,
    `</section>`,
    `<section>`,
    `<h2>Experience</h2>`,
    `<div>`,
    `<h3>Front-End Developer at ABC Company</h3>`,
    `<p>Worked on developing user-friendly and responsive web applications using React.</p>`,
    `<p>Collaborated with designers to implement pixel-perfect UI designs.</p>`,
    `</div>`,
    `<div>`,
    `<h3>Web Developer Intern at XYZ Agency</h3>`,
    `<p>Assisted in the development of web projects, gaining hands-on experience with HTML, CSS, and JavaScript.</p>`,
    `</div>`,
    `</section>`,
    `<section>`,
    `<h2>Education</h2>`,
    `<div>`,
    `<h3>Bachelor of Science in Computer Science</h3>`,
    `<p>University of Front-End Development</p>`,
    `<p>Graduated Magna Cum Laude</p>`,
    `</div>`,
    `</section>`,
    `<section>`,
    `<h2>Contact</h2>`,
    `<p>Email: john.doe@example.com</p>`,
    `<p>LinkedIn: <a href="https://www.linkedin.com/in/johndoe" target="_blank">linkedin.com/in/johndoe</a></p>`,
    `</section>`
  ]
}